// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEfUdbxPBAm3aJklxsHk1jlKXT12vyB0',
    appId: '1:84978133802:web:18ac6e7ff2a525391c0c53',
    messagingSenderId: '84978133802',
    projectId: 'personalfinances-18a74',
    authDomain: 'personalfinances-18a74.firebaseapp.com',
    storageBucket: 'personalfinances-18a74.appspot.com',
    measurementId: 'G-055VJZ47PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEk7aiTty5n2W3kFRa6aisKSS_MWko5N8',
    appId: '1:84978133802:android:8e0b7ea6a45bf3291c0c53',
    messagingSenderId: '84978133802',
    projectId: 'personalfinances-18a74',
    storageBucket: 'personalfinances-18a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6jDlNFfyFHE8MyCjts5wh56KhgWQBaM',
    appId: '1:84978133802:ios:7895f8b80f8805e61c0c53',
    messagingSenderId: '84978133802',
    projectId: 'personalfinances-18a74',
    storageBucket: 'personalfinances-18a74.appspot.com',
    iosClientId: '84978133802-087ima3m3l5l8vv7j3fh3rp5cijnejq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6jDlNFfyFHE8MyCjts5wh56KhgWQBaM',
    appId: '1:84978133802:ios:7895f8b80f8805e61c0c53',
    messagingSenderId: '84978133802',
    projectId: 'personalfinances-18a74',
    storageBucket: 'personalfinances-18a74.appspot.com',
    iosClientId: '84978133802-087ima3m3l5l8vv7j3fh3rp5cijnejq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinances',
  );
}
